# Generated by Django 3.2.3 on 2021-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210530_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='films.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='directors', to='films.Director'),
        ),
    ]
