# Generated by Django 3.2.3 on 2021-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20210531_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.URLField(default='data/generic.png'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='films.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.Director'),
        ),
    ]
