# Generated by Django 3.2.3 on 2021-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210531_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
