# Generated by Django 3.2.3 on 2021-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='available_in_countries',
            field=models.ManyToManyField(blank=True, related_name='available_in_countries', to='films.Country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
