# Generated by Django 3.2.3 on 2021-06-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
    ]
