<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-06-30 15:25
=======
# Generated by Django 3.2.3 on 2021-06-24 15:13
>>>>>>> f8cc9b8503b2e0b147baa2f24d5d11890618f4e6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
    ]
